module.exports = {
  "access_secret_key": "53iaedwhzpzWxcKbPItiq2cYZFYQuSA45P2lB0NasdaAOEscaBo1x4RnaFbhDHVS82HsagdafasaujtGWAy1IdAkuLGmyv1BZyRBH3sLdiB3TvjYdcWvrkY9TzXJmFBAAz",
  "refresh_secret_key": "yS7JutOUs0pofGs3P1J45tfHfGsFMJU8TRgvxflcFhNCrWWMKozCfvVO9cwO8DZcBzt1yy1JsKMDIZSGMTcb9NfbUKX6UdXjvTkJ"
}