apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-test-deployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: sejutacita
        image: andresetiawan/sejutacita_test:1.0
        ports:
        - containerPort: 8002